// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/buscar-empresas.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const key = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_ANON_KEY",
    "VITE_SUPABASE_ANON_KEY"
  ]);
  if (!key) {
    throw new Error("SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ANON_KEY) is required");
  }
  return key;
}
function supabaseForUser(ctx) {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "No autenticado." }],
    isError: true
  };
}

// src/lib/mcp/tools/buscar-empresas.ts
var buscar_empresas_default = defineTool({
  name: "buscar_empresas",
  title: "Buscar empresas",
  description: "Busca empresas del radar comercial por nombre, CIF, sector, localidad u operador y devuelve sus datos clave (l\xEDneas, score, estado telecom).",
  inputSchema: {
    query: z.string().trim().min(1).describe("Texto a buscar en nombre, CIF, sector o localidad."),
    limit: z.number().int().min(1).max(50).default(20).describe("M\xE1ximo de resultados (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const q = `%${query.replace(/\s+/g, "%")}%`;
    const { data, error } = await supabase.from("companies").select(
      "id,name,cif,sector,employees,localidad,provincia,address,operador_actual,operador_fijo,lineas_movil,lineas_fijo,lineas_total,opportunity_score,is_hot"
    ).or(`name.ilike.${q},cif.ilike.${q},sector.ilike.${q},localidad.ilike.${q}`).order("opportunity_score", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { empresas: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/ficha-empresa.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
var ficha_empresa_default = defineTool2({
  name: "ficha_empresa",
  title: "Ficha de empresa",
  description: "Devuelve la ficha completa de una empresa (datos telecom, contactos, decisores), sus sedes, su lead en el pipeline y sus ventas cerradas.",
  inputSchema: {
    company_id: z2.string().trim().min(1).describe("ID de la empresa (campo id de companies).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const [company, sedes, leads, sales] = await Promise.all([
      supabase.from("companies").select("*").eq("id", company_id).maybeSingle(),
      supabase.from("sedes").select("*").eq("company_id", company_id),
      supabase.from("leads").select("*").eq("company_id", company_id),
      supabase.from("sales").select("*").eq("company_id", company_id).order("fecha", { ascending: false })
    ]);
    const err = company.error ?? sedes.error ?? leads.error ?? sales.error;
    if (err) return { content: [{ type: "text", text: err.message }], isError: true };
    if (!company.data) {
      return { content: [{ type: "text", text: "Empresa no encontrada." }], isError: true };
    }
    const payload = {
      empresa: company.data,
      sedes: sedes.data ?? [],
      leads: leads.data ?? [],
      ventas: sales.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/listar-pipeline.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
var ESTADOS = [
  "lead",
  "contactado",
  "cualificado",
  "propuesta",
  "negociacion",
  "ganada",
  "perdida"
];
var listar_pipeline_default = defineTool3({
  name: "listar_pipeline",
  title: "Listar pipeline",
  description: "Lista los leads del pipeline comercial del usuario, opcionalmente filtrados por estado (lead, contactado, cualificado, propuesta, negociacion, ganada, perdida).",
  inputSchema: {
    estado: z3.enum(ESTADOS).optional().describe("Estado del pipeline por el que filtrar."),
    limit: z3.number().int().min(1).max(100).default(50).describe("M\xE1ximo de leads a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estado, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select(
      "id,company_id,empresa,cif,sector,tamano,estado,opportunity_score,next_action,next_action_date,notas,updated_at"
    ).order("opportunity_score", { ascending: false }).limit(limit ?? 50);
    if (estado) query = query.eq("estado", estado);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/actualizar-lead.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^4.4.3";
var actualizar_lead_default = defineTool4({
  name: "actualizar_lead",
  title: "Actualizar lead del pipeline",
  description: "Cambia el estado del pipeline de un lead y/o su pr\xF3xima acci\xF3n y notas. Escribe \xFAnicamente en la tabla leads.",
  inputSchema: {
    lead_id: z4.string().trim().min(1).describe("ID del lead a actualizar."),
    estado: z4.enum(ESTADOS).optional().describe("Nuevo estado del pipeline."),
    next_action: z4.string().trim().max(500).optional().describe("Pr\xF3xima acci\xF3n comercial."),
    next_action_date: z4.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Fecha de la pr\xF3xima acci\xF3n (YYYY-MM-DD)."),
    notas: z4.string().trim().max(4e3).optional().describe("Notas del lead.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id, estado, next_action, next_action_date, notas }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const patch = { updated_at: (/* @__PURE__ */ new Date()).toISOString() };
    if (estado !== void 0) patch.estado = estado;
    if (next_action !== void 0) patch.next_action = next_action;
    if (next_action_date !== void 0) patch.next_action_date = next_action_date;
    if (notas !== void 0) patch.notas = notas;
    if (Object.keys(patch).length === 1) {
      return { content: [{ type: "text", text: "Nada que actualizar." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").update(patch).eq("id", lead_id).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: "Lead no encontrado o sin permisos." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0], null, 2) }],
      structuredContent: { lead: data[0] }
    };
  }
});

// src/lib/mcp/tools/registrar-venta.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^4.4.3";
var registrar_venta_default = defineTool5({
  name: "registrar_venta",
  title: "Registrar venta cerrada",
  description: "Registra una venta cerrada de una empresa (l\xEDneas m\xF3vil, fibras, SNAV, margen y si es producto estrat\xE9gico). Alimenta los KPIs del trimestre en la pesta\xF1a Hoy.",
  inputSchema: {
    company_id: z5.string().trim().min(1).describe("ID de la empresa."),
    lineas_movil: z5.number().int().min(0).default(0).describe("Altas de l\xEDneas m\xF3viles."),
    lineas_fibra: z5.number().int().min(0).default(0).describe("Altas de fibras."),
    snav: z5.number().min(0).default(0).describe("SNAV en euros."),
    margen: z5.number().min(0).default(0).describe("Margen en euros."),
    producto: z5.string().trim().max(200).optional().describe("Producto vendido."),
    producto_estrategico: z5.boolean().default(false).describe("Si es producto estrat\xE9gico acelerador."),
    fecha: z5.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Fecha de la venta (YYYY-MM-DD). Por defecto hoy."),
    notas: z5.string().trim().max(2e3).optional().describe("Notas de la venta.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sales").insert({
      company_id: input.company_id,
      lineas_movil: input.lineas_movil ?? 0,
      lineas_fibra: input.lineas_fibra ?? 0,
      snav: input.snav ?? 0,
      margen: input.margen ?? 0,
      producto: input.producto ?? null,
      producto_estrategico: input.producto_estrategico ?? false,
      ...input.fecha ? { fecha: input.fecha } : {},
      notas: input.notas ?? null
    }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? {}, null, 2) }],
      structuredContent: { venta: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/kpis-ventas.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z6 } from "npm:zod@^4.4.3";
var kpis_ventas_default = defineTool6({
  name: "kpis_ventas",
  title: "KPIs de ventas del periodo",
  description: "Agrega las ventas cerradas en un rango de fechas: altas de l\xEDneas m\xF3viles y fibras, SNAV total, margen total y rentabilidad media por l\xEDnea.",
  inputSchema: {
    desde: z6.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Fecha inicial (YYYY-MM-DD)."),
    hasta: z6.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Fecha final (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ desde, hasta }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sales").select("lineas_movil,lineas_fibra,snav,margen,producto_estrategico").gte("fecha", desde).lte("fecha", hasta);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const altasMovil = rows.reduce((a, r) => a + (r.lineas_movil ?? 0), 0);
    const altasFibra = rows.reduce((a, r) => a + (r.lineas_fibra ?? 0), 0);
    const altas = altasMovil + altasFibra;
    const snav = rows.reduce((a, r) => a + Number(r.snav ?? 0), 0);
    const margen = rows.reduce((a, r) => a + Number(r.margen ?? 0), 0);
    const estrategicas = rows.filter((r) => r.producto_estrategico).length;
    const kpis = {
      ventas: rows.length,
      altas_movil: altasMovil,
      altas_fibra: altasFibra,
      altas_totales: altas,
      snav_total: Math.round(snav * 100) / 100,
      margen_total: Math.round(margen * 100) / 100,
      rentabilidad_media_linea: altas ? Math.round(margen / altas * 100) / 100 : 0,
      ventas_estrategicas: estrategicas
    };
    return {
      content: [{ type: "text", text: JSON.stringify(kpis, null, 2) }],
      structuredContent: kpis
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mojjwrwzowpflmhqfhsh";
var mcp_default = defineMcp({
  name: "proyecto-nexus",
  title: "Proyecto Nexus",
  version: "0.1.0",
  instructions: "Herramientas del CRM comercial B2B telco Nexus (Grupo Enertel). Busca empresas del radar, consulta su ficha completa (sedes, contactos, ventas), gestiona el pipeline en espa\xF1ol (lead, contactado, cualificado, propuesta, negociacion, ganada, perdida), registra ventas cerradas y consulta KPIs del periodo. Todas las operaciones act\xFAan como el usuario autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [buscar_empresas_default, ficha_empresa_default, listar_pipeline_default, actualizar_lead_default, registrar_venta_default, kpis_ventas_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
